### ISSUE TITLE
Itt nincsen semmi

### ISSUE THREAD

**Issue by Legolaszstudio** [Bagaci05/PrivatDiscordTheme#1]
### Jó napot uram!

Várható, hogy lesz itt valami? Kiváncsi vagyok arra a privát discord témára!

Üdv,
Novy Levi

**Comment by Bagaci05** [comment]
öhm ja. Réjöttem, hogy mi a fasznak rakjam fel githubra, onnan úgyis többidő betölteni. Mert amikor néztem ezeket, hogy írják a css-ben mindig github linkre utaltak. és gondoltam megcsinálom. csak nem tudom, hogy tudok css-ben lekérni egy másik css filet, githubról. RIP

**Comment by Legolaszstudio** [comment]
RIP
